export const navbar = [
    {
        name:'home',
        link:'/',
        label:'home'
    },
    {
        name:'about',
        link:'',
        label:'about'
    },
    {
        name:'domains',
        link:'',
        label:'domains'
    },
    {
        name:'mentors',
        link:'',
        label:'mentors'
    },
    {
        name:'events',
        link:'',
        label:'events'
    },
    {
        name:'teams',
        link:'',
        label:'teams'
    },
    {
        name:'contactus',
        link:'',
        label:'contact us'
    },
    {
        name:'login',
        link:'/auth',
        label:'login'
    },
]

export const login = [
    {
        name:'email',
        type:'email',
    },
    {
        name:'pasword',
        type:'pasword',
    },
]